<section class="executive-hero">
    <div><span class="section-kicker">Rapports Construction</span><h2>Analyse consolidée des chantiers</h2><p>Suivi portefeuille, coûts consommés, marges réelles estimées et alertes de dépassement.</p></div>
    <div class="executive-summary"><span>Projets critiques</span><strong><?= (int) $dashboard['critical_count']; ?></strong><small><?= number_format($dashboard['average_progress'], 1, ',', ' '); ?>% avancement moyen</small></div>
</section>
<section class="kpi-grid executive-kpis">
    <article class="kpi-card"><div class="kpi-meta"><span>Contrats</span><span class="badge badge-success">Total</span></div><strong><?= money($dashboard['contract_total']); ?></strong><small>Portefeuille</small></article>
    <article class="kpi-card"><div class="kpi-meta"><span>Prévisionnel</span><span class="badge badge-neutral">Budget</span></div><strong><?= money($dashboard['forecast_total']); ?></strong><small>Coûts prévus</small></article>
    <article class="kpi-card"><div class="kpi-meta"><span>Réel consommé</span><span class="badge badge-warning">Réalisé</span></div><strong><?= money($dashboard['actual_total']); ?></strong><small>Consommations + dépenses</small></article>
    <article class="kpi-card"><div class="kpi-meta"><span>Projets actifs</span><span class="badge badge-success">En cours</span></div><strong><?= (int) $dashboard['active_count']; ?></strong><small>Chantiers actifs</small></article>
</section>
<section class="panel"><div class="panel-header"><div><span class="section-kicker">Synthèse</span><h3>Projets et marges</h3></div></div><div class="table-responsive"><table class="data-table"><thead><tr><th>Projet</th><th>Statut</th><th class="text-right">Avancement</th><th class="text-right">Coût réel</th><th class="text-right">Marge réelle</th><th class="text-right">Retard</th></tr></thead><tbody><?php foreach ($dashboard['projects'] as $project): ?><tr><td><?= e($project['reference']); ?> · <?= e($project['name']); ?></td><td><span class="badge <?= project_status_badge($project['status']); ?>"><?= e(status_label($project['status'])); ?></span></td><td class="text-right"><?= number_format($project['metrics']['physical_progress'], 1, ',', ' '); ?>%</td><td class="text-right"><?= money($project['metrics']['actual_cost']); ?></td><td class="text-right"><?= money($project['metrics']['actual_margin']); ?></td><td class="text-right"><?= (int) $project['metrics']['delay_days']; ?> j</td></tr><?php endforeach; ?></tbody></table></div></section>
