<section class="executive-hero">
    <div><span class="section-kicker">Placement</span><h2>Rapports Placement de Personnel</h2><p>Vue rapide des agents placés, clients, revenus, coûts et marges WAKE.</p></div>
    <div class="executive-summary"><span>Agents actifs placés</span><strong><?= (int) $metrics['active_agents']; ?></strong><small><?= (int) $metrics['invoice_count']; ?> factures générées</small></div>
</section>
<section class="kpi-grid executive-kpis">
    <article class="kpi-card"><div class="kpi-meta"><span>Factures générées</span><span class="badge badge-success">CA</span></div><strong><?= money($metrics['invoice_total']); ?></strong><small>Total facturé</small></article>
    <article class="kpi-card"><div class="kpi-meta"><span>Marge facturée</span><span class="badge badge-success">Marge</span></div><strong><?= money($metrics['invoice_margin']); ?></strong><small>Marge sur factures</small></article>
    <article class="kpi-card"><div class="kpi-meta"><span>Contrats actifs</span><span class="badge badge-neutral">Clients</span></div><strong><?= count($metrics['contracts']); ?></strong><small>Contrats enregistrés</small></article>
    <article class="kpi-card"><div class="kpi-meta"><span>Expirant bientôt</span><span class="badge badge-warning">30 jours</span></div><strong><?= count($metrics['expiring']); ?></strong><small>À renouveler</small></article>
</section>
<section class="dashboard-grid"><article class="panel"><div class="panel-header"><div><span class="section-kicker">Marge par agent</span><h3>Agents placés</h3></div></div><div class="table-responsive"><table class="data-table"><thead><tr><th>Agent</th><th>Client</th><th class="text-right">Coût</th><th class="text-right">Tarif</th><th class="text-right">Marge</th></tr></thead><tbody><?php foreach ($employees as $e): ?><tr><td><?= e($e['first_name'] . ' ' . $e['last_name']); ?></td><td><?= e($e['client_name'] ?? '-'); ?></td><td class="text-right"><?= money($e['base_salary']); ?></td><td class="text-right"><?= $e['client_rate'] ? money($e['client_rate']) : '-'; ?></td><td class="text-right"><?= $e['margin_amount'] ? money($e['margin_amount']) : '-'; ?></td></tr><?php endforeach; ?></tbody></table></div></article><article class="panel"><div class="panel-header"><div><span class="section-kicker">Contrats</span><h3>Contrats expirant bientôt</h3></div></div><div class="stack-list"><?php foreach ($metrics['expiring'] as $contract): ?><div class="stack-item"><div><strong><?= e($contract['client_name']); ?></strong><small><?= e($contract['reference']); ?> · fin <?= e($contract['end_date']); ?></small></div><span class="badge badge-warning">Renouveler</span></div><?php endforeach; ?><?php if ($metrics['expiring'] === []): ?><div class="empty-state compact"><p>Aucun contrat n’expire bientôt.</p></div><?php endif; ?></div></article></section>

