<section class="panel">
    <div class="panel-header"><div><span class="section-kicker"><?= e($report['project_reference']); ?></span><h2>Rapport du <?= e($report['report_date']); ?></h2></div><a class="btn btn-secondary" href="<?= url('construction/projects/show?id=' . (int) $report['construction_project_id']); ?>">Retour cockpit</a></div>
    <div class="detail-grid"><article><span>Projet</span><strong><?= e($report['project_name']); ?></strong></article><article><span>Météo</span><strong><?= e($report['weather'] ?? '-'); ?></strong></article><article><span>Créé par</span><strong><?= e($report['created_by_name']); ?></strong></article><article><span>Date</span><strong><?= e($report['created_at']); ?></strong></article></div>
    <p class="detail-purpose"><strong>Remarques :</strong><br><?= nl2br(e($report['remarks'] ?? '-')); ?><br><br><strong>Blocages :</strong><br><?= nl2br(e($report['blockers'] ?? '-')); ?></p>
</section>
<section class="dashboard-grid">
    <article class="panel"><div class="panel-header"><div><span class="section-kicker">Travaux</span><h3>Quantités réalisées</h3></div></div><div class="table-responsive"><table class="data-table"><thead><tr><th>Travail</th><th>Exécuté</th><th class="text-right">Qté</th><th class="text-right">Progression</th></tr></thead><tbody><?php foreach ($progress as $row): ?><tr><td><?= e($row['task_name']); ?></td><td><?= e($row['executed_work']); ?></td><td class="text-right"><?= e($row['quantity_done']); ?> <?= e($row['unit']); ?></td><td class="text-right"><?= e($row['progress_percent']); ?>%</td></tr><?php endforeach; ?></tbody></table></div></article>
    <article class="panel"><div class="panel-header"><div><span class="section-kicker">Consommations</span><h3>Matériaux utilisés</h3></div></div><div class="stack-list"><?php foreach ($consumptions as $row): ?><div class="stack-item"><div><strong><?= e($row['material_name']); ?></strong><small><?= e($row['quantity_used']); ?> <?= e($row['unit']); ?> · PU <?= money($row['unit_cost']); ?></small></div><span class="amount-text"><?= money($row['total_cost']); ?></span></div><?php endforeach; ?></div></article>
</section>
<section class="dashboard-grid">
    <article class="panel"><div class="panel-header"><div><span class="section-kicker">Dépenses</span><h3>Dépenses du jour</h3></div></div><div class="stack-list"><?php foreach ($expenses as $expense): ?><div class="stack-item"><div><strong><?= e($expense['category']); ?></strong><small><?= e($expense['description']); ?></small></div><span class="amount-text"><?= money($expense['amount']); ?></span></div><?php endforeach; ?></div></article>
    <article class="panel"><div class="panel-header"><div><span class="section-kicker">Photos</span><h3>Photos chantier</h3></div></div><div class="photo-grid"><?php foreach ($photos as $photo): ?><a href="<?= rtrim(PUBLIC_URL, '/') . '/' . e($photo['file_path']); ?>" target="_blank"><img src="<?= rtrim(PUBLIC_URL, '/') . '/' . e($photo['file_path']); ?>" alt="<?= e($photo['caption'] ?? 'Photo chantier'); ?>"></a><?php endforeach; ?></div></article>
</section>

